### ISSUE TITLE
Shield blocking arrow sound

### ISSUE THREAD

**Issue by iPyronic** [SpigotMC/SpigotCraft#119]
In singleplayer, shields make a sound when you block an arrow that was shot at you (the same sound as blocking a melee attack). This sound is not played while blocking an arrow on the test server.

**Comment by md-5** [comment]
And in Vanilla?

**Comment by iPyronic** [comment]
Vanilla server? Sorry, I haven't tried it there yet D:

**Comment by iPyronic** [comment]
Just tested it on a vanilla pre-release 3 server. The sound plays there too (like in singleplayer). Just not on the spigot server.

**Additional info:** Requires survival mode or adventure mode. Vanilla doesn't play a sound when blocking in creative mode.

**Comment by md-5** [comment]
Finally solved it

**Comment by Combustible** [comment]
This bug seems to still exist with spigot (tested with no plugins) since at least 1.11

Additionally, there is a slightly delay where an arrow that hits a shield is "suspended" and lowering your shield again causes you to get hit by the arrow. This happens in vanilla minecraft too, but the time period is much smaller.
