### ISSUE TITLE
Creative-Inv in Survival

### ISSUE THREAD

**Issue by Andre601** [SpigotMC/SpigotCraft#263]
I encountered this bug, while i was on the creative-plots.

After I used /spawn, I still had the inventory of the creative-world.

**Comment by antoniojamore** [comment]
This also happened to me.

**Comment by klugemonkey** [comment]
Confirmed.  And, XP particles earned on Creative stay with you.

**Comment by klugemonkey** [comment]
However, this is not a bug.  It's just that the server is setup with a separate world for Creative instead of a separate server.  There is no way to have separate inventories and XP levels for different worlds on the same bukkit instance.  I would suppose one could write a plugin to save and restore inventories when warping to other worlds, but why bother.

**Comment by Pokechu22** [comment]
Yea, there are plugins for that purpose, but it's a _test_ server; it's not too important.

**Comment by yannicklamprecht** [comment]
One that is called multiverse-inventories. Is this still available?

**Comment by chuushi** [comment]
MV-Inv was disbanded, and they're recommending Per World Inventories as replacement.
