### ISSUE TITLE
Essentials Give Not Working with New Blocks

### ISSUE THREAD

**Issue by ghost** [SpigotMC/SpigotCraft#327]
I can't seem to give myself a debug stick, it would be very interesting to play around with it, see if it works and so on.

I tryed to give it do myself but it doesn't work. Actually no new blocks work with Essentials, and even with blocks that previously existed, for example the andesite block as it is a completely new block now and not a data value of stone.

**Comment by ghost** [comment]
I need a debug stick :'(

**Comment by md-5** [comment]
Essentials is a legacy plugin, at this time it’s not meant to work with new items and blocks because there is no guarantee that it’s able to handle them properly.
I will look into why andesite is not working and if it’s possible to fix (there are edge cases that are irrecoverable due to the original api).

**Comment by md-5** [comment]
Andesite etc fixed for next release
