### ISSUE TITLE
Clicking on Redstone-Blocks in Recipebook causes Serverlag

### ISSUE THREAD

**Issue by MrSpock78** [SpigotMC/SpigotCraft#347]
I tested with 4 stacks redstonedust in inventory in survival mode.
Using a workbench and clicking multiple times on the redstone-block in recipebook cause a serverlag.
The craftable redstoneblock is just blinking and the amount is not shown.

In singleplayer vanilla this is not happening.

- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version
- [x] Bug does not exist on current Spigot version

**Comment by md-5** [comment]
Half vanilla bug, half our bug. The auto recipe is ridiculously inefficient, and us running some aggressive conversions of ItemStacks tipped it over the edge. Because data values are no longer used, our conversions were a bit over the top, so I've scaled them back for the next release.

Just need to double check that loading old serialized items works
