### ISSUE TITLE
Doing /rtp results in death, was working on 9June2018

### ISSUE THREAD

**Issue by GlenBuie** [SpigotMC/SpigotCraft#408]
SpigotCraft Issue Template
==========================

- Please ensure that you have verified that the bug you are reporting exists on the current Vanilla snapshot before reporting.
- It is also appreciated if you can verify the presence or absence of the bug on the current release Spigot version.
- Make sure that information is as detailed as possible so that others can reproduce your issue even if they are unfamiliar with the concepts involved.

Please fill out the appropriate checkboxes below confirming the testing you have done:
---
- [X] Bug exists on current Vanilla snapshot
- [ ] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.12.2)
- [?] Bug does not exist on current Spigot version (1.12.2)
---
Signed on 12Jun2018 @ 6pm CDT, tried /rtp, failed & died.
See attached screenshot, impossible tp coordinates!
Sorry, didn't intend to break it.

![screenshot from 2018-06-12 18-01-01](https://user-images.githubusercontent.com/5025597/41322204-586b4c70-6e6d-11e8-8dd1-e97a99751c6d.png)

**Comment by md-5** [comment]
Server was last updated 8th June, so its unlikely this was a code change causing the issue

**Comment by JeepSmash** [comment]
I have found that Spigot "moved wrongly" messages often appears in my console when players are teleported with plugins.  If the teleport coordinates are somewhat close (not accounting for world changes) it will rubber band them back to previous coordinates but if the player changed their world it will impose the new coordinates into the new world (not take them back to the original world).  The code that is checking player movements is not accounting for teleports or world changes and will make corrections to player coords when it should not be.  I know that /rtp should not be changing the world but it may be related to the issue i am having which places my players over the void in my skyblock worlds.

My temporary fix (as a plugin dev):
Repeatedly teleport the player every tick for 10 ticks to account for 'adjustments' of the players location since it seems random in my testing how many ticks it may be before its 'adjustment'.

Needed FIX:
Restart the Moved Wrongly checks if a teleport or portal event occurs or at least save the world of the coords for rubberbanding
