### ISSUE TITLE
Explosions not exploding

### ISSUE THREAD

**Issue by ShaneBeee** [SpigotMC/SpigotCraft#467]
- [ ] Bug exists on current Vanilla snapshot
- [x] Bug does not exist on current Vanilla snapshot
- [ ] Bug exists on current Spigot version (1.14.4)
- [x] Bug does not exist on current Spigot version (1.14.4)

Seems explosions are not working.
I tested this all above and below sea level in the event that GriefPrevention is preventing explosions above sea level.
These may all possibly be plugin related.

**TNT**
Lighting a TNT, it fizzles, then as it is about to explode, it just disappears. 
They also don't damage entities and they do not ignite nearby TNT

**CREEPERS**
They explode, they damage other entities but they do not damage blocks.

**END CRYSTAL**
They do not explode. They make no noise, they do not destroy blocks, but they do damage/kill nearby entities.

**Comment by md-5** [comment]
Pretty sure this is just GriefPrevention

**Comment by ShaneBeee** [comment]
I was thinking that, since GP threw some messages for the TNT I think, but I don't remember this behaviour before, on 1.14.4.

If I was able to test it off this server I would, but I can't so I'll have to wait til you post a public release, and I'll do more testing. :)

**Comment by Puremin0rez** [comment]
Assuming the GP config on this repo is the same as the server:
https://github.com/SpigotMC/SpigotCraft/blob/master/plugins/GriefPreventionData/config.yml

GP should only be preventing explosions above surface level and on any height in a claim, so if explosions are being affected on all heights and outside of claims, then maybe it's either a GP failure, plugin conflict or actual server issue.


Edit: and of course just as I look at that, I see WorldGuard is running on the server with all forms of explosions disabled:
https://github.com/SpigotMC/SpigotCraft/blob/master/plugins/WorldGuard/config.yml

So most likely, WorldGuard is flat out blocking all explosions regardless of situation since that's how it's configured currently.
