### ISSUE TITLE
Skeleton AI stuck

### ISSUE THREAD

**Issue by thijsa** [SpigotMC/SpigotCraft#97]
I was walking through the map when I saw a skeleton at day light. So I walked to the skeleton, but it didn't attacked me, and it didn't catched fire from the sun. I couldn't attack the skeleton.
Screenshots:
https://i.thijsalders.nl/WYTpXwzVV
https://i.thijsalders.nl/a4vfnY6dG
https://i.thijsalders.nl/3kAAoI0AF
https://i.thijsalders.nl/bHeoNY6wk
(The skeletons you see in the distance on the last picture are attacking normally)
Video:
https://www.youtube.com/watch?v=fqcEpmbtH24

**Comment by 0x277F** [comment]
I can confirm this issue exists and I'm pretty sure md is already aware of it. If I had to make a guess without seeing the new 1.9 code, I'd guess the culprit was something to do with async chunk loading. I have no idea why it only affects skeletons, but I think it's possible that the skeletons are not being completely loaded into the world somehow.

**Comment by mechoriet** [comment]
its like 6 hours later and the skeleton is still stuck on its place still not hittable i goed its broken entity

i`m the only one on the server it located @ 326 64 324 so the chunks should be reloaded in a way 

or not cuz there spawn protected chunks

**Comment by mechoriet** [comment]
![2015-12-31_23 44 30](https://cloud.githubusercontent.com/assets/4313219/12068883/8230a2aa-b018-11e5-9098-415b879ea40e.png)
its a floating skeleton

**Comment by ghost** [comment]
I believe this is a 1.9 bug. Same thing happened in my vanilla 15w51b server.

**Comment by HeroCC** [comment]
Found another one just a bit from spawn on the official server

**Comment by Puremin0rez** [comment]
This was fixed today in 1.9 PR2
https://bugs.mojang.com/browse/MC-91290
